# Primeiros Passos
Lembre-se de utilizar `pip install numpy` em seu terminal para instalar a biblioteca do NumPy, caso sua distribuição Python não seja Anaconda ou alguma outra que já venha com bibliotecas padrão instaladas.

Após instalar, o comando para importar o numpy é o padrão para qualquer biblioteca Python, com `import numpy`, sendo recomendado também utilizar um apelido com `as np`, como no código abaixo. Dessa forma, poderá invocar todas as ferramentas do NumPy através do apelido especificado.
> Posso utilizar qualquer apelido? — você pergunta

Pode. Utilize `import numpy as kurisutina` se quiser, então todas as vezes que precisar invocar as ferramentas do NumPy utilizará `kurisutina.show_config()`, por exemplo. Contudo, apesar de ser possível, não é recomendado — siga sempre as boas práticas de código limpo e legível. **np** é o apelido padrão utilizado para o NumPy e será reconhecido em qualquer canto no mundo.

In [1]:
import numpy as np

Tendo importado o NumPy, podemos verificar alguns atributos importantes dele. O NumPy vem com diversos atributos e métodos úteis para obtermos informações acerca dele. Alguns exemplos podem ser conferidos abaixo:

In [2]:
print(f"Versão do NumPy: {np.__version__} \n") # Comando utilizado para verificar a versão do NumPy que está rodando
print(f"Documentação: {np.__doc__[:200]}... \n") # Comando utilizado para exibir a documentação do NumPy no console. Repare que utilizando `[:200]` foi ordenado que apenas os 200 primeiros caracteres fossem exibidos.
print(f"Diretório do Arquivo: {np.__file__} \n") # Comando que exibe o diretório onde NumPy está instalado
print(f"Diretório do Cachê: {np.__cached__} \n") # Comando para exibir o diretório onde os arquivos de cachê estão armazenados
print(f"Carregador do Módulo: {np.__loader__} \n") # Comando que mostra como o Python carregou o NumPy
print(f"Pacote: {np.__package__} \n") # Mostra o nome do Pacote
print(f"Nome do módulo: {np.__name__} \n") # Mostra o nome do Módulo

print("\nConfiguração de Compilação:")
np.show_config() # Exibe informações de como o NumPy foi compilado

Versão do NumPy: 2.3.5 

Documentação: 
NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use t... 

Diretório do Arquivo: /home/annamozart/anaconda3/lib/python3.13/site-packages/numpy/__init__.py 

Diretório do Cachê: /home/annamozart/anaconda3/lib/python3.13/site-packages/numpy/__pycache__/__init__.cpython-313.pyc 

Carregador do Módulo: <_frozen_importlib_external.SourceFileLoader object at 0x7f94c3e86f30> 

Pacote: numpy 

Nome do módulo: numpy 


Configuração de Compilação:
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /home/annamozart/anaconda3/include
    lib directory: /home/annamozart/anaconda3/lib
    name: mkl-sdl
    openblas configuration: unknown
    pc file directory: /home/annamozart/anaconda3/lib/pkgconfig
    version: '2025'
  lapack:
    detection method: pkgconfig
    foun

# N-Dimensional Array
N-Dimensional Arrays, ou **ndarrays**, são a base da biblioteca do NumPy. Eles são um objeto que se assemelha muito a uma *Lista* Python, mas são extremamente mais poderosos e eficientes em uso de memória e velocidade. A biblioteca do NumPy gira em torno deles, portanto, é vital que você masterize os ndarrays. No bloco de código abaixo podemos ver como criar um ndarray e como realizar determinadas operações com ele.

In [3]:
# Criando nosso primeiro ndarray
arr = np.array([1, 2, 3, 4, 5]) # Array NumPy
lis = [1, 2, 3, 4, 5] # Lista em Python, para compararmos

print(f"Array: {arr}") # Exibe o Array NumPy
print(f"Lista: {lis}\n") # Exibe a Lista Python
print(f"Tipo do Array: {type(arr)}") # Exibe tipo de objeto do Array NumPy
print(f"Tipo da Lista: {type(lis)}\n") # Exibe tipo de objeto da Lista Python
print(f"Tamanho do Array: {arr.shape}")  # Mostra o tamanho do Array NumPy
print(f"Tamanho da List: {len(lis)}\n")  # Mostra o tamanho da Lista Python (Repare que o comando utilizado não foi 'shape' pois Listas não o possuem)
print(f"Tipo dos dados: {arr.dtype}") # Mostra o tipo dos elementos
print(f"Listas não possuem 'dtype' pois são capazes de armazenar objetos de diferentes tipos de dados")  

Array: [1 2 3 4 5]
Lista: [1, 2, 3, 4, 5]

Tipo do Array: <class 'numpy.ndarray'>
Tipo da Lista: <class 'list'>

Tamanho do Array: (5,)
Tamanho da List: 5

Tipo dos dados: int64
Listas não possuem 'dtype' pois são capazes de armazenar objetos de diferentes tipos de dados


> Mas então, qual a vantagem de usar Arrays NumPy ao invés de Listas?

## Vantagens dos NArrays

### Eficiência
O núcleo das operações numéricas é implementado em C (Apesar de ser uma biblioteca Python), ou seja, programação de baixo nível. Isso eleva sua eficiência para cálculos numéricos de forma titânica. Comparado a uma Lista, que é gerenciada pelo interpretador do Python e cada elemento é um objeto Python, os arrays do Numpy operam quase ao nível do hardware e cada elemento é armazenado como binário puro, sendo bem melhores no gerenciamento de memória e velocidade de processamento.
> Eu não acredito!

Pois acredite... Veja no código abaixo exemplos comparando a velocidade entre Listas e arrays do Numpy.


In [4]:
import time
import random

# Cria uma Lista e um NArray com valores idênticos, de forma aleatória
elist = [random.random() for _ in range(1_000_000)]
enarray = np.array(elist)

# --- Teste 1: Soma de elementos ---
# Lista
start = time.time()
elist_sum = sum(elist)
elist_time = time.time() - start

# NArray
start = time.time()
narray_sum = np.sum(enarray)
narray_time = time.time() - start

print(f"Soma - Lista: {elist_time:.6f}s, NArray: {narray_time:.6f}s")
print(f"Speedup: {elist_time / narray_time:.2f}x")

# --- Teste 2: Operações elemento a elemento ---
# Lista (comprehension)
start = time.time()
nova_lista = [x * 2 for x in elist]
elist_time = time.time() - start

# NArray (vetorizado)
start = time.time()
novo_narray = enarray * 2
narray_time = time.time() - start

print(f"\nMultiplicação - Lista: {elist_time:.6f}s, NArray: {narray_time:.6f}s")
print(f"Speedup: {elist_time / narray_time:.2f}x")

# --- Teste 3: Cálculos complexos (ex: exponencial) ---
from math import exp

# Lista
start = time.time()
exp_lista = [exp(x) for x in elist]
elist_time = time.time() - start

# NArray
start = time.time()
exp_narray = np.exp(enarray)
narray_time = time.time() - start

print(f"\nExponencial - Lista: {elist_time:.6f}s, NArray: {narray_time:.6f}s")
print(f"Speedup: {elist_time / narray_time:.2f}x")

Soma - Lista: 0.005246s, NArray: 0.000531s
Speedup: 9.89x

Multiplicação - Lista: 0.028497s, NArray: 0.001694s
Speedup: 16.82x

Exponencial - Lista: 0.036829s, NArray: 0.001540s
Speedup: 23.92x



### Homogêneidade
Arrays NumPy são homogêneos, isto é, só podem armazenar dados de um único tipo. Como Listas podem possuir elementos de diferentes tipos, o acesso aos dados é mais lento pois o interpretador precisa verificar o tipo de cada elemento individualmente. Arrays NumPy não precisam passar por essa etapa a mais pois todos os elementos certamente serão sempre do mesmo tipo.
### Vetorizações
Como todos os dados de um Array NumPy pertencem a um mesmo tipo, também podemos aplicar **Vetorizações**, uma técnica para realizar diversas operações matemáticas a todos os elementos de uma só vez, sem precisar utilizar um Loop para percorrer cada um individualmente (Como é necessário em Listas). Exemplos de vetorização podem ser conferidos abaixo:

In [5]:
print(f"Array: {arr}") # Exibe o Array NumPy

# Operações são aplicadas a TODOS os elementos automaticamente
print("\n--- Operações Aritméticas Vetorizadas ---")
arrsum = arr + 10
print("Array + 10: ", arrsum) # Soma 10 a todos os elementos do Array NumPy

product = arr * 10
print("Array * 10: ", product) # Multplica 10 a todos os elementos do Array NumPy

power = arr ** 2
print("Array ao quadrado: ", power) # Eleva ao quadrado todos os elementos do Array NumPy

###
lista = [1, 2, 3, 4, 5]
quadrados = []
for x in lista:
    quadrados.append(x ** 2)
###

print("\n--- Operações Estatísticas ---")
print("Média do Array: ", np.mean(arr)) # Tira a média de todos os elementos do Array NumPy
print("Soma total: ", np.sum(arr)) # Soma todos os elementos do Array NumPy
print("Valor máximo: ", np.max(arr)) # Pega o maior valor do Array NumPy
print("Valor mínimo: ", np.min(arr)) # Pega o menor valor do Array NumPy

Array: [1 2 3 4 5]

--- Operações Aritméticas Vetorizadas ---
Array + 10:  [11 12 13 14 15]
Array * 10:  [10 20 30 40 50]
Array ao quadrado:  [ 1  4  9 16 25]

--- Operações Estatísticas ---
Média do Array:  3.0
Soma total:  15
Valor máximo:  5
Valor mínimo:  1


In [6]:
array_1d = np.array([1, 2, 3, 4, 5])
print(array_1d.ndim)
print(array_1d.shape)
print(array_1d)

array_2d = np.array([[1, 2, 3], [4, 5, 6]])
print(array_2d.ndim)
print(array_2d.shape)
print(array_2d)

array_3d = np.array([[[1, 2], [3, 4], [5, 6], [7, 8]]])
print(array_3d.ndim)
print(array_3d.shape)
print(array_3d)

array_4d = np.array([[[[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]]]])
print(array_4d.ndim)
print(array_4d.shape)
print(array_4d)



#np.zeros(): Para criar arrays preenchidos com zeros.

# np.ones(): Para criar arrays preenchidos com uns.

# np.arange(): Semelhante ao range do Python, mas retorna um ndarray.

# np.linspace(): Para criar sequências de números igualmente espaçadas.


1
(5,)
[1 2 3 4 5]
2
(2, 3)
[[1 2 3]
 [4 5 6]]
3
(1, 4, 2)
[[[1 2]
  [3 4]
  [5 6]
  [7 8]]]
4
(1, 1, 6, 2)
[[[[ 1  2]
   [ 3  4]
   [ 5  6]
   [ 7  8]
   [ 9 10]
   [11 12]]]]


I'M ON THE RADIO

DU HAST

In [7]:
array_index = np.array([[1, 1, 2], [3, 5, 8], [13, 21, 34]])
print(array_index[2,1])
element = array_index[1,0]
print(element)
print(array_index[2,:])
print(array_index[:, 1])
sub_array = array_index[0:3,1:3]
print(sub_array)
filtered_bool_array = array_index > 7
print(filtered_bool_array)
filtered_array = array_index[filtered_bool_array]
print(filtered_array)
filtered_array.ndim

array_index_2 = array_index
print(array_index_2)
array_index[1,1] = 99
print(array_index)
print(array_index_2)
array_index_2[1,1] = 144
print(array_index)

21
3
[13 21 34]
[ 1  5 21]
[[ 1  2]
 [ 5  8]
 [21 34]]
[[False False False]
 [False False  True]
 [ True  True  True]]
[ 8 13 21 34]
[[ 1  1  2]
 [ 3  5  8]
 [13 21 34]]
[[ 1  1  2]
 [ 3 99  8]
 [13 21 34]]
[[ 1  1  2]
 [ 3 99  8]
 [13 21 34]]
[[  1   1   2]
 [  3 144   8]
 [ 13  21  34]]


In [8]:
array_index
sliced_line = array_index[0:2, :]
sliced_line
sliced_column = array_index[:, 0:2]
sliced_column
subarray = array_index[0:2, 0:2]
subarray
print(array_index)
array_index[0:2, 0:2] = [[-66, -42],[72, -2]]
print(array_index)

array_index[1:3, 1:3] = [[0, 0],[0, 0]]
print(array_index)

[[  1   1   2]
 [  3 144   8]
 [ 13  21  34]]
[[-66 -42   2]
 [ 72  -2   8]
 [ 13  21  34]]
[[-66 -42   2]
 [ 72   0   0]
 [ 13   0   0]]
