# Primeiros Passos
Lembre-se de utilizar `pip install numpy` em seu terminal para instalar a biblioteca do NumPy, caso sua distribuição Python não seja Anaconda ou alguma outra que já venha com bibliotecas padrão instaladas.

Após instalar, o comando para importar o numpy é o padrão para qualquer biblioteca Python, com `import numpy`, sendo recomendado também utilizar um apelido com `as np`, como no código abaixo. Dessa forma, poderá invocar todas as ferramentas do NumPy através do apelido especificado.
> Posso utilizar qualquer apelido? — você pergunta

Pode. Utilize `import numpy as kurisutina` se quiser, então todas as vezes que precisar invocar as ferramentas do NumPy utilizará `kurisutina.show_config()`, por exemplo. Contudo, apesar de ser possível, não é recomendado — siga sempre as boas práticas de código limpo e legível. **np** é o apelido padrão utilizado para o NumPy e será reconhecido em qualquer canto no mundo.

In [ ]:
import numpy as np

Tendo importado o NumPy, podemos verificar alguns atributos importantes dele. O NumPy vem com diversos atributos e métodos úteis para obtermos informações acerca dele. Alguns exemplos podem ser conferidos abaixo:

In [ ]:
print(f"Versão do NumPy: {np.__version__} \n") # Comando utilizado para verificar a versão do NumPy que está rodando
print
print(f"Documentação: {np.__doc__[:200]}... \n") # Comando utilizado para exibir a documentação do NumPy no console. Repare que utilizando `[:200]` foi ordenado que apenas os 200 primeiros caracteres fossem exibidos.
print(f"Diretório do Arquivo: {np.__file__} \n") # Comando que exibe o diretório onde NumPy está instalado
print(f"Diretório do Cachê: {np.__cached__} \n") # Comando para exibir o diretório onde os arquivos de cachê estão armazenados
print(f"Carregador do Módulo: {np.__loader__} \n") # Comando que mostra como o Python carregou o NumPy
print(f"Pacote: {np.__package__} \n") # Mostra o nome do Pacote
print(f"Nome do módulo: {np.__name__} \n") # Mostra o nome do Módulo

print("\nConfiguração de Compilação:")
np.show_config() # Exibe informações de como o NumPy foi compilado

Versão do NumPy: 2.1.3 

Documentação: 
NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use t... 

Diretório do Arquivo: c:\Users\Intel I5\anaconda3\Lib\site-packages\numpy\__init__.py 

Diretório do Cachê: c:\Users\Intel I5\anaconda3\Lib\site-packages\numpy\__pycache__\__init__.cpython-313.pyc 

Carregador do Módulo: <_frozen_importlib_external.SourceFileLoader object at 0x0000020C17E704D0> 

Pacote: numpy 

Nome do módulo: numpy 


Configuração de compilação:
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/Intel I5/anaconda3/Library/include
    lib directory: C:/Users/Intel I5/anaconda3/Library/lib
    name: mkl-sdl
    openblas configuration: unknown
    pc file directory: C:\b\abs_25aj347ekn\croot\numpy_and_numpy_base_1730835595898\_h_env\Library\lib\pkgconfig
    version: '2023.

IT'S A VIOLENT PO.....

In [184]:
arr = np.array([1, 2, 3, 4, 5])
print("Array: ", arr)
print("Tipo Array: ", type(arr))
sum = arr + 10
print("Soma do Array: ", sum)
product = arr * 10
print("Multiplicação do Array: ", product)
arrmean = np.mean(arr)
print("Média do Array: ", arrmean)

Array:  [1 2 3 4 5]
Tipo Array:  <class 'numpy.ndarray'>
Soma do Array:  [11 12 13 14 15]
Multiplicação do Array:  [10 20 30 40 50]
Média do Array:  3.0


In [185]:
array_1d = np.array([1, 2, 3, 4, 5])
print(array_1d.ndim)
print(array_1d.shape)
print(array_1d)

array_2d = np.array([[1, 2, 3], [4, 5, 6]])
print(array_2d.ndim)
print(array_2d.shape)
print(array_2d)

array_3d = np.array([[[1, 2], [3, 4], [5, 6], [7, 8]]])
print(array_3d.ndim)
print(array_3d.shape)
print(array_3d)

array_4d = np.array([[[[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]]]])
print(array_4d.ndim)
print(array_4d.shape)
print(array_4d)


1
(5,)
[1 2 3 4 5]
2
(2, 3)
[[1 2 3]
 [4 5 6]]
3
(1, 4, 2)
[[[1 2]
  [3 4]
  [5 6]
  [7 8]]]
4
(1, 1, 6, 2)
[[[[ 1  2]
   [ 3  4]
   [ 5  6]
   [ 7  8]
   [ 9 10]
   [11 12]]]]


I'M ON THE RADIO

In [186]:
array_index = np.array([[1, 1, 2], [3, 5, 8], [13, 21, 34]])
print(array_index[2,1])
element = array_index[1,0]
print(element)
print(array_index[2,:])
print(array_index[:, 1])
sub_array = array_index[0:3,1:3]
print(sub_array)
filtered_bool_array = array_index > 7
print(filtered_bool_array)
filtered_array = array_index[filtered_bool_array]
print(filtered_array)
filtered_array.ndim

array_index_2 = array_index
print(array_index_2)
array_index[1,1] = 99
print(array_index)
print(array_index_2)
array_index_2[1,1] = 144
print(array_index)

21
3
[13 21 34]
[ 1  5 21]
[[ 1  2]
 [ 5  8]
 [21 34]]
[[False False False]
 [False False  True]
 [ True  True  True]]
[ 8 13 21 34]
[[ 1  1  2]
 [ 3  5  8]
 [13 21 34]]
[[ 1  1  2]
 [ 3 99  8]
 [13 21 34]]
[[ 1  1  2]
 [ 3 99  8]
 [13 21 34]]
[[  1   1   2]
 [  3 144   8]
 [ 13  21  34]]
