BANANA BANANA BANANA BANANA TERRACOTA BANANA TERRACOTA TERRACOTA PIE

In [2]:
import numpy as np
np.__version__

'2.1.3'

IT'S A VIOLENT PO.....

In [3]:
arr = np.array([1, 2, 3, 4, 5])
print("Array: ", arr)
print("Tipo Array: ", type(arr))
sum = arr + 10
print("Soma do Array: ", sum)
product = arr * 10
print("Multiplicação do Array: ", product)
arrmean = np.mean(arr)
print("Média do Array: ", arrmean)

Array:  [1 2 3 4 5]
Tipo Array:  <class 'numpy.ndarray'>
Soma do Array:  [11 12 13 14 15]
Multiplicação do Array:  [10 20 30 40 50]
Média do Array:  3.0


In [4]:
array_1d = np.array([1, 2, 3, 4, 5])
print(array_1d.ndim)
print(array_1d.shape)
print(array_1d)

array_2d = np.array([[1, 2, 3], [4, 5, 6]])
print(array_2d.ndim)
print(array_2d.shape)
print(array_2d)

array_3d = np.array([[[1, 2], [3, 4], [5, 6], [7, 8]]])
print(array_3d.ndim)
print(array_3d.shape)
print(array_3d)

array_4d = np.array([[[[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]]]])
print(array_4d.ndim)
print(array_4d.shape)
print(array_4d)


1
(5,)
[1 2 3 4 5]
2
(2, 3)
[[1 2 3]
 [4 5 6]]
3
(1, 4, 2)
[[[1 2]
  [3 4]
  [5 6]
  [7 8]]]
4
(1, 1, 6, 2)
[[[[ 1  2]
   [ 3  4]
   [ 5  6]
   [ 7  8]
   [ 9 10]
   [11 12]]]]


I'M ON THE RADIO

In [27]:
array_index = np.array([[1, 1, 2], [3, 5, 8], [13, 21, 34]])
print(array_index[2,1])
element = array_index[1,0]
print(element)
print(array_index[2,:])
print(array_index[:, 1])
sub_array = array_index[0:3,1:3]
print(sub_array)
filtered_bool_array = array_index > 7
print(filtered_bool_array)
filtered_array = array_index[filtered_bool_array]
print(filtered_array)
filtered_array.ndim

array_index_2 = array_index
print(array_index_2)
array_index[1,1] = 99
print(array_index)
print(array_index_2)
array_index_2[1,1] = 144
print(array_index)

21
3
[13 21 34]
[ 1  5 21]
[[ 1  2]
 [ 5  8]
 [21 34]]
[[False False False]
 [False False  True]
 [ True  True  True]]
[ 8 13 21 34]
[[ 1  1  2]
 [ 3  5  8]
 [13 21 34]]
[[ 1  1  2]
 [ 3 99  8]
 [13 21 34]]
[[ 1  1  2]
 [ 3 99  8]
 [13 21 34]]
[[  1   1   2]
 [  3 144   8]
 [ 13  21  34]]
