# Importar o NumPy
Lembre-se de utilizar `pip install numpy` em seu terminal para instalar a biblioteca do NumPy, caso sua distribuição Python não seja Anaconda ou alguma outra que já venha com bibliotecas padrão instaladas.

Após instalar, o comando para importar o numpy é o padrão para qualquer biblioteca Python, com `import numpy`, sendo recomendado também utilizar um apelido com `as np`, como no código abaixo. Dessa forma, poderá invocar todas as ferramentas do NumPy através do apelido especificado.
> Posso utilizar qualquer apelido? — você pergunta

Pode. Utilize `import numpy as kurisutina` se quiser, então todas as vezes que precisar invocar as ferramentas do NumPy utilizará `kurisutina.show_config()`, por exemplo. Contudo, apesar de ser possível, não é recomendado — siga sempre as boas práticas de código limpo e legível. **np** é o apelido padrão utilizado para o NumPy e será reconhecido em qualquer canto no mundo.

In [ ]:
import numpy as np

In [80]:
np.__version__
np.__doc__
np.__file__
np.__cached__
np.__loader__
np.__package__
np.__name__
np.version.version
np.version.git_revision
np.show_config()
np.__dict__.keys()

Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/Intel I5/anaconda3/Library/include
    lib directory: C:/Users/Intel I5/anaconda3/Library/lib
    name: mkl-sdl
    openblas configuration: unknown
    pc file directory: C:\b\abs_25aj347ekn\croot\numpy_and_numpy_base_1730835595898\_h_env\Library\lib\pkgconfig
    version: '2023.1'
  lapack:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/Intel I5/anaconda3/Library/include
    lib directory: C:/Users/Intel I5/anaconda3/Library/lib
    name: mkl-sdl
    openblas configuration: unknown
    pc file directory: C:\b\abs_25aj347ekn\croot\numpy_and_numpy_base_1730835595898\_h_env\Library\lib\pkgconfig
    version: '2023.1'
Compilers:
  c:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30156
  c++:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30156
  cython:
    commands: cython
    linker: cython
    nam

dict_keys(['__name__', '__doc__', '__package__', '__loader__', '__spec__', '__path__', '__file__', '__cached__', '__builtins__', '_utils', '_globals', '_NoValue', '_CopyMode', '_expired_attrs_2_0', '__expired_attributes__', 'version', '__version__', '__NUMPY_SETUP__', '_distributor_init', 'exceptions', 'dtypes', '_pytesttester', '_core', '__config__', 'show_config', 'False_', 'ScalarType', 'True_', '_get_promotion_state', '_no_nep50_warning', '_set_promotion_state', 'abs', 'absolute', 'acos', 'acosh', 'add', 'all', 'allclose', 'amax', 'amin', 'any', 'arange', 'arccos', 'arccosh', 'arcsin', 'arcsinh', 'arctan', 'arctan2', 'arctanh', 'argmax', 'argmin', 'argpartition', 'argsort', 'argwhere', 'around', 'array', 'array2string', 'array_equal', 'array_equiv', 'array_repr', 'array_str', 'asanyarray', 'asarray', 'ascontiguousarray', 'asfortranarray', 'asin', 'asinh', 'atan', 'atanh', 'atan2', 'astype', 'atleast_1d', 'atleast_2d', 'atleast_3d', 'base_repr', 'binary_repr', 'bitwise_and', 'bitwis

IT'S A VIOLENT PO.....

In [81]:
arr = np.array([1, 2, 3, 4, 5])
print("Array: ", arr)
print("Tipo Array: ", type(arr))
sum = arr + 10
print("Soma do Array: ", sum)
product = arr * 10
print("Multiplicação do Array: ", product)
arrmean = np.mean(arr)
print("Média do Array: ", arrmean)

Array:  [1 2 3 4 5]
Tipo Array:  <class 'numpy.ndarray'>
Soma do Array:  [11 12 13 14 15]
Multiplicação do Array:  [10 20 30 40 50]
Média do Array:  3.0


In [82]:
array_1d = np.array([1, 2, 3, 4, 5])
print(array_1d.ndim)
print(array_1d.shape)
print(array_1d)

array_2d = np.array([[1, 2, 3], [4, 5, 6]])
print(array_2d.ndim)
print(array_2d.shape)
print(array_2d)

array_3d = np.array([[[1, 2], [3, 4], [5, 6], [7, 8]]])
print(array_3d.ndim)
print(array_3d.shape)
print(array_3d)

array_4d = np.array([[[[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]]]])
print(array_4d.ndim)
print(array_4d.shape)
print(array_4d)


1
(5,)
[1 2 3 4 5]
2
(2, 3)
[[1 2 3]
 [4 5 6]]
3
(1, 4, 2)
[[[1 2]
  [3 4]
  [5 6]
  [7 8]]]
4
(1, 1, 6, 2)
[[[[ 1  2]
   [ 3  4]
   [ 5  6]
   [ 7  8]
   [ 9 10]
   [11 12]]]]


I'M ON THE RADIO

In [83]:
array_index = np.array([[1, 1, 2], [3, 5, 8], [13, 21, 34]])
print(array_index[2,1])
element = array_index[1,0]
print(element)
print(array_index[2,:])
print(array_index[:, 1])
sub_array = array_index[0:3,1:3]
print(sub_array)
filtered_bool_array = array_index > 7
print(filtered_bool_array)
filtered_array = array_index[filtered_bool_array]
print(filtered_array)
filtered_array.ndim

array_index_2 = array_index
print(array_index_2)
array_index[1,1] = 99
print(array_index)
print(array_index_2)
array_index_2[1,1] = 144
print(array_index)

21
3
[13 21 34]
[ 1  5 21]
[[ 1  2]
 [ 5  8]
 [21 34]]
[[False False False]
 [False False  True]
 [ True  True  True]]
[ 8 13 21 34]
[[ 1  1  2]
 [ 3  5  8]
 [13 21 34]]
[[ 1  1  2]
 [ 3 99  8]
 [13 21 34]]
[[ 1  1  2]
 [ 3 99  8]
 [13 21 34]]
[[  1   1   2]
 [  3 144   8]
 [ 13  21  34]]
